#Minecraft server properties
#Thu Mar 26 11:34:51 GMT 2026
spawn-protection=10
max-tick-time=600000
query.port=8081
generator-settings=
force-gamemode=false
allow-nether=true
enforce-whitelist=false
gamemode=0
broadcast-console-to-ops=true
enable-query=true
player-idle-timeout=30
difficulty=1
spawn-monsters=true
op-permission-level=4
resource-pack-hash=
announce-player-achievements=true
pvp=false
snooper-enabled=true
level-type=default
hardcore=false
enable-command-block=true
network-compression-threshold=256
max-players=20
resource-pack-sha1=
max-world-size=29999984
server-port=8081
server-ip=
spawn-npcs=true
allow-flight=true
level-name=world
view-distance=5
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=false
max-build-height=256
level-seed=
use-native-transport=true
enable-rcon=false
motd=\u00A77Welcome to the server of \u00A79R12JP12\u00A77\!
